- hosts: all
  become: true
  become_method: sudo
  vars:
    keystore_password: changemepl3453
  roles:
    - { role: cmprescott.xml }
    - { role: CSCfi.jetty }
    - { role: CSCfi.shibboleth-idp-v1.1.8, configurables: ['consent','nameid', 'oidc'], scope: csc.fi, port: 8443, bport: 8444, keystore_password: changemepl3453 }
    - { role: mpass-proxy }

